version: 2.1
jobs:
  build:
    docker:
      - image: peaceiris/mdbook
    steps:
      - checkout
      - run:
          name: Build Book
          command: mdbook build
    
  deploy:
    docker:
      - image: node
    steps:
      - run: ls
      - run:
          name: Install wrangler
          command: npm install -g wrangler
      - run:
          name: Upload
          command: npx wrangler pages publish book --project-name=calculus-guide
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
