version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Install curl
          command: apt-get update && apt-get install curl -y
      - run:
          name: Install rust
          command: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: source "$HOME/.cargo/env"
      - run:
          name: Install and build book
          command: cargo install mdbook && mdbook build
      - run: ls
      - run:
          name: Install node
          command: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - run:
          name: Install wrangler
          command: npm install -g wrangler
      - run:
          name: Upload
          command: npx wrangler pages publish book --project-name=calculus-guide
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
